DROP TABLE IF EXISTS song_genres;
DROP TABLE IF EXISTS song_credits;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS users;
DROP FUNCTION IF EXISTS set_updated_at();
